'use client'
import {useEffect,useState} from 'react'
import { getSupabase } from '@/lib/supabase-browser'

const accept='.mp3,.m4a,.mp4a,.wav,audio/mpeg,audio/mp4,audio/wav'

type Tab='Studio'|'Master'|'Mix'|'Mashup'|'Generate'|'Library'
function Uploader({multiple=false,onFiles}:{multiple?:boolean,onFiles:(f:File[])=>void}){return <div className="drop"><label><input type="file" accept={accept} multiple={multiple} onChange={e=>onFiles(Array.from(e.target.files||[]))}/>Choose audio files</label><div className="muted" style={{marginTop:10}}>MP3, M4A/MP4A or WAV • up to 100 MB</div></div>}

export default function Home(){
 const [tab,setTab]=useState<Tab>('Studio'); const [files,setFiles]=useState<File[]>([]); const [status,setStatus]=useState(''); const [prompt,setPrompt]=useState(''); const [user,setUser]=useState<any>(null); const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [jobs,setJobs]=useState<any[]>([])
 useEffect(()=>{getSupabase().auth.getUser().then(({data})=>setUser(data.user)); const {data}=getSupabase().auth.onAuthStateChange((_e,s)=>setUser(s?.user??null)); return ()=>data.subscription.unsubscribe()},[])
 async function auth(mode:'in'|'up'){setStatus(''); const r=mode==='in'?await getSupabase().auth.signInWithPassword({email,password}):await getSupabase().auth.signUp({email,password}); if(r.error)setStatus(r.error.message); else setStatus(mode==='in'?'Signed in.':'Account created — check your email if confirmation is enabled.')}
 async function uploadAndRun(operation:'master'|'mix'|'mashup'){
   if(!user){setStatus('Sign in to process audio.');return}
   const needed=operation==='master'?1:operation==='mashup'?2:1
   if(files.length!==needed){setStatus(operation==='master'?'Upload one file.':operation==='mashup'?'Upload exactly two files.':'Upload at least one track.');return}
   setStatus('Uploading securely to Sonora…')
   const paths:string[]=[]
   for(const f of files){if(f.size>100*1024*1024){setStatus(`${f.name} is larger than 100 MB.`);return}; const safe=f.name.replace(/[^a-zA-Z0-9._-]/g,'_'); const path=`${user.id}/${crypto.randomUUID()}-${safe}`; const {error}=await getSupabase().storage.from('sonora-audio').upload(path,f,{contentType:f.type||'audio/*',upsert:false}); if(error){setStatus(error.message);return}; paths.push(path)}
   setStatus('Creating AI job…')
   const token=(await getSupabase().auth.getSession()).data.session?.access_token
   const r=await fetch(`/api/${operation}`,{method:'POST',headers:{Authorization:`Bearer ${token}`,'content-type':'application/json'},body:JSON.stringify({paths,names:files.map(f=>f.name)})})
   const j=await r.json(); setStatus(j.message||j.status||j.error||'Job submitted.'); if(r.ok) loadJobs()
 }
 async function generate(){if(!user){setStatus('Sign in to generate songs.');return} if(prompt.trim().length<3){setStatus('Describe your song first.');return} setStatus('Creating generation job…'); const token=(await getSupabase().auth.getSession()).data.session?.access_token; const r=await fetch('/api/generate',{method:'POST',headers:{Authorization:`Bearer ${token}`,'content-type':'application/json'},body:JSON.stringify({prompt,duration:120,instrumental:false})}); const j=await r.json(); setStatus(j.message||j.status||j.error||'Generation job submitted.'); if(r.ok) loadJobs()}
 async function loadJobs(){if(!user)return; const token=(await getSupabase().auth.getSession()).data.session?.access_token; const r=await fetch('/api/jobs',{headers:{Authorization:`Bearer ${token}`}}); if(r.ok)setJobs(await r.json())}
 useEffect(()=>{if(!user)return; loadJobs(); const t=setInterval(loadJobs,5000); return ()=>clearInterval(t)},[user])
 async function signOut(){await getSupabase().auth.signOut();setUser(null);setJobs([]);setStatus('Signed out.')}
 const title=tab==='Generate'?'Create a song':tab==='Library'?'Your library':tab==='Studio'?'Create with AI':'Shape your sound'
 return <div className="shell"><aside className="side"><div className="brand">SONORA <span>AI</span></div><div className="nav">{(['Studio','Master','Mix','Mashup','Generate','Library'] as Tab[]).map(x=><button className={tab===x?'active':''} onClick={()=>setTab(x)} key={x}>{x}</button>)}</div><div style={{position:'absolute',bottom:22,left:28,right:28}} className="muted">{user?<>Signed in as<br/>{user.email}</>:<>AI music workspace<br/>Creator beta</>}</div></aside><main className="main"><div className="top"><div><div className="pill">AI Music Studio</div><h1 style={{marginTop:12}}>{title}</h1></div>{user?<button className="btn secondary" onClick={signOut}>Sign out</button>:<div className="auth"><input placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)}/><input placeholder="Password" type="password" value={password} onChange={e=>setPassword(e.target.value)}/><button className="btn" onClick={()=>auth('in')}>Sign in</button><button className="btn secondary" onClick={()=>auth('up')}>Create account</button></div>}</div><div className="grid">
 {tab==='Studio'?<><section className="card big"><h2>Everything you need to make music</h2><p className="muted">Upload, master, mix, mash up or generate. Sonora stores your jobs and audio privately in your account.</p><div className="studio-grid">{[['Master','Polish a finished track'],['Mix','Balance stems and tracks'],['Mashup','Blend two songs'],['Generate','Create from a prompt']].map(([x,d])=><button className="feature" key={x} onClick={()=>setTab(x as Tab)}><b>{x}</b><span>{d}</span></button>)}</div></section><section className="card"><h2>AI workflow</h2><p className="muted">Secure upload → job queue → licensed AI provider → result → private library.</p><div className="meter"><i/></div><div className="muted">{user?'Connected to Supabase':'Sign in to activate cloud jobs'}</div></section></>:tab==='Generate'?<section className="card big"><h2>AI Song Generator</h2><p className="muted">Describe the genre, mood, vocals, instruments and arrangement.</p><textarea className="prompt" value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder="A cinematic electronic track with warm synths, female vocals, rising chorus…"/><div className="actions"><button className="btn" onClick={generate}>Generate song</button><button className="btn secondary" onClick={()=>setPrompt('')}>Clear</button></div><div className="status">{status}</div></section>:tab==='Library'?<section className="card big"><h2>Your AI jobs</h2>{jobs.length?<div className="jobs">{jobs.map(j=><div className="job" key={j.id}><b>{j.job_type}</b><span>{j.status}</span><small>{new Date(j.created_at).toLocaleString()}</small>{j.metadata?.output_url&&<audio controls src={j.metadata.output_url} style={{width:'100%',marginTop:8}}/>}</div>)}</div>:<p className="muted">No jobs yet. Create your first master, mix, mashup or song.</p>}<button className="btn secondary" onClick={loadJobs}>Refresh</button></section>:<><section className="card big"><h2>{tab==='Master'?'AI Sound Master':tab==='Mix'?'AI Sound Mixing':'AI Mashup Maker'}</h2><p className="muted">{tab==='Master'?'Upload one track and submit it to your mastering pipeline.':tab==='Mix'?'Upload tracks and submit a mixing job.':'Upload exactly two tracks and create a mashup job.'}</p><Uploader multiple={tab!=='Master'} onFiles={setFiles}/>{files.length>0&&<div className="file">{files.map(f=><div key={f.name}>♪ {f.name}</div>)}</div>}<div className="actions"><button className="btn" onClick={()=>uploadAndRun(tab==='Master'?'master':tab==='Mix'?'mix':'mashup')}>Start AI {tab}</button><button className="btn secondary" onClick={()=>{setFiles([]);setStatus('')}}>Reset</button></div><div className="status">{status}</div></section><section className="card"><h2>AI signal chain</h2><p className="muted">Input analysis → tonal balance → dynamics → loudness → delivery.</p><div className="meter"><i/></div><div className="muted">Pipeline ready</div></section></>}
 </div><div className="footer">Sonora AI • Private Supabase audio storage • Provider-agnostic AI pipeline.</div></main></div>
}
